
[workspace]
resolver = "1"
members = [
    "udi",
    "udi-sys",
    "udiprops_parse",
    "udi_macros",
    "udi_macro_helpers",
    "tools/fix_elf",
    "samples/udi_env",
    "samples/net_ne2000",
    #"samples/net_rtl8139",
    ]
exclude = [
    "samples/net_rtl8139",
    ]