
udi_strcpy = 0;
udi_strncpy_rtrim = 0;

udi_channel_spawn = 0;
udi_channel_event_complete = 0;
udi_buf_write = 0;
udi_buf_copy = 0;
udi_usage_res = 0;
udi_enumerate_ack = 0;

udi_cb_alloc = 0;
udi_cb_alloc_batch = 0;

udi_pio_map = 0;
udi_pio_trans = 0;
udi_bus_bind_req = 0;
udi_intr_attach_req = 0;
udi_intr_event_rdy = 0;

udi_gio_bind_ack = 0;
udi_gio_unbind_ack = 0;
udi_gio_xfer_ack = 0;
udi_gio_xfer_nak = 0;
udi_gio_event_ind = 0;