[package]
name = "udi-net_rtl8139"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib","rlib"]
test = false    # Tests don't link becuase there's no UDI environment

[dependencies]
udi = { path = "../../" }
[build-dependencies]
udiprops_parse = { path = "../../udiprops_parse" }
