[package]
name = "udi-net_ne2000"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib","rlib"]

[dependencies]
udi = { path = "../../" }
[build-dependencies]
udiprops_parse = { path = "../../udi_udiprops_parse" }
