[package]
name = "udi-net_ne2000"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib","rlib"]
test = false    # Tests don't link becuase there's no UDI environment

[dependencies]
udi = { path = "../../udi" }
[build-dependencies]
udiprops_parse = { path = "../../udiprops_parse" }
